// Generated by go-wayland-scanner
// https://github.com/Nomadcxx/sysc-wayland/cmd/sysc-wayland-scanner
// XML file : ../../../../protocols/ext-background-effect-v1.xml
//
// ext_background_effect_v1 Protocol Copyright:
//
// Copyright (C) 2015 Martin Gräßlin
// Copyright (C) 2015 Marco Martin
// Copyright (C) 2020 Vlad Zahorodnii
// Copyright (C) 2024 Xaver Hugl
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package backgroundeffect

import "github.com/Nomadcxx/sysc-wayland/client"

// ExtBackgroundEffectManagerV1InterfaceName is the name of the interface as it appears in the [client.Registry].
// It can be used to match the [client.RegistryGlobalEvent.Interface] in the
// [Registry.SetGlobalHandler] and can be used in [Registry.Bind] if this applies.
const ExtBackgroundEffectManagerV1InterfaceName = "ext_background_effect_manager_v1"

// ExtBackgroundEffectManagerV1 : background effect factory
//
// This protocol provides a way to improve visuals of translucent surfaces
// by applying effects like blur to the background behind them.
//
// The capabilities are send when the global is bound, and every time they
// change. Note that when the capability goes away, the corresponding effect
// is no longer applied by the compositor, even if it was set before.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
type ExtBackgroundEffectManagerV1 struct {
	client.BaseProxy
	capabilitiesHandler ExtBackgroundEffectManagerV1CapabilitiesHandlerFunc
}

// NewExtBackgroundEffectManagerV1 : background effect factory
//
// This protocol provides a way to improve visuals of translucent surfaces
// by applying effects like blur to the background behind them.
//
// The capabilities are send when the global is bound, and every time they
// change. Note that when the capability goes away, the corresponding effect
// is no longer applied by the compositor, even if it was set before.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
func NewExtBackgroundEffectManagerV1(ctx *client.Context) *ExtBackgroundEffectManagerV1 {
	extBackgroundEffectManagerV1 := &ExtBackgroundEffectManagerV1{}
	ctx.Register(extBackgroundEffectManagerV1)
	return extBackgroundEffectManagerV1
}

// Destroy : destroy the background effect manager
//
// Informs the server that the client will no longer be using this
// protocol object. Existing objects created by this object are not
// affected.
func (i *ExtBackgroundEffectManagerV1) Destroy() error {
	defer i.MarkZombie()
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetBackgroundEffect : get a background effects object
//
// Instantiate an interface extension for the given wl_surface to add
// effects like blur for the background behind it.
//
// If the given wl_surface already has a ext_background_effect_surface_v1
// object associated, the background_effect_exists protocol error will be
// raised.
//
//	surface: the surface
func (i *ExtBackgroundEffectManagerV1) GetBackgroundEffect(surface *client.Surface) (*ExtBackgroundEffectSurfaceV1, error) {
	id := NewExtBackgroundEffectSurfaceV1(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

type ExtBackgroundEffectManagerV1Error uint32

// ExtBackgroundEffectManagerV1Error :
const (
	// ExtBackgroundEffectManagerV1ErrorBackgroundEffectExists : the surface already has a background effect object
	ExtBackgroundEffectManagerV1ErrorBackgroundEffectExists ExtBackgroundEffectManagerV1Error = 0
)

func (e ExtBackgroundEffectManagerV1Error) Name() string {
	switch e {
	case ExtBackgroundEffectManagerV1ErrorBackgroundEffectExists:
		return "background_effect_exists"
	default:
		return ""
	}
}

func (e ExtBackgroundEffectManagerV1Error) Value() string {
	switch e {
	case ExtBackgroundEffectManagerV1ErrorBackgroundEffectExists:
		return "0"
	default:
		return ""
	}
}

func (e ExtBackgroundEffectManagerV1Error) String() string {
	return e.Name() + "=" + e.Value()
}

type ExtBackgroundEffectManagerV1Capability uint32

// ExtBackgroundEffectManagerV1Capability :
const (
	// ExtBackgroundEffectManagerV1CapabilityBlur : the compositor supports applying blur
	ExtBackgroundEffectManagerV1CapabilityBlur ExtBackgroundEffectManagerV1Capability = 0
)

func (e ExtBackgroundEffectManagerV1Capability) Name() string {
	switch e {
	case ExtBackgroundEffectManagerV1CapabilityBlur:
		return "blur"
	default:
		return ""
	}
}

func (e ExtBackgroundEffectManagerV1Capability) Value() string {
	switch e {
	case ExtBackgroundEffectManagerV1CapabilityBlur:
		return "0"
	default:
		return ""
	}
}

func (e ExtBackgroundEffectManagerV1Capability) String() string {
	return e.Name() + "=" + e.Value()
}

// ExtBackgroundEffectManagerV1CapabilitiesEvent : capabilities of the compositor
type ExtBackgroundEffectManagerV1CapabilitiesEvent struct {
	Flags uint32
}
type ExtBackgroundEffectManagerV1CapabilitiesHandlerFunc func(ExtBackgroundEffectManagerV1CapabilitiesEvent)

// SetCapabilitiesHandler : sets handler for ExtBackgroundEffectManagerV1CapabilitiesEvent
func (i *ExtBackgroundEffectManagerV1) SetCapabilitiesHandler(f ExtBackgroundEffectManagerV1CapabilitiesHandlerFunc) {
	i.capabilitiesHandler = f
}

func (i *ExtBackgroundEffectManagerV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.capabilitiesHandler == nil {
			return
		}
		var e ExtBackgroundEffectManagerV1CapabilitiesEvent
		l := 0
		e.Flags = client.Uint32(data[l : l+4])
		l += 4

		i.capabilitiesHandler(e)
	default:
		panic("client: unsupported opcode")
	}
}

// ExtBackgroundEffectSurfaceV1InterfaceName is the name of the interface as it appears in the [client.Registry].
// It can be used to match the [client.RegistryGlobalEvent.Interface] in the
// [Registry.SetGlobalHandler] and can be used in [Registry.Bind] if this applies.
const ExtBackgroundEffectSurfaceV1InterfaceName = "ext_background_effect_surface_v1"

// ExtBackgroundEffectSurfaceV1 : background effects for a surface
//
// The background effect object provides a way to specify a region behind
// a surface that should have background effects like blur applied.
//
// If the wl_surface associated with the ext_background_effect_surface_v1
// object has been destroyed, this object becomes inert.
type ExtBackgroundEffectSurfaceV1 struct {
	client.BaseProxy
}

// NewExtBackgroundEffectSurfaceV1 : background effects for a surface
//
// The background effect object provides a way to specify a region behind
// a surface that should have background effects like blur applied.
//
// If the wl_surface associated with the ext_background_effect_surface_v1
// object has been destroyed, this object becomes inert.
func NewExtBackgroundEffectSurfaceV1(ctx *client.Context) *ExtBackgroundEffectSurfaceV1 {
	extBackgroundEffectSurfaceV1 := &ExtBackgroundEffectSurfaceV1{}
	ctx.Register(extBackgroundEffectSurfaceV1)
	return extBackgroundEffectSurfaceV1
}

// Destroy : release the blur object
//
// Informs the server that the client will no longer be using this protocol
// object. The effect regions will be removed on the next commit.
func (i *ExtBackgroundEffectSurfaceV1) Destroy() error {
	defer i.MarkZombie()
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetBlurRegion : set blur region
//
// This request sets the region of the surface that will have its
// background blurred.
//
// The blur region is specified in the surface-local coordinates, and
// clipped by the compositor to the surface size.
//
// The initial value for the blur region is empty. Setting the pending
// blur region has copy semantics, and the wl_region object can be
// destroyed immediately. A NULL wl_region removes the effect.
//
// The blur region is double-buffered state, and will be applied on
// the next wl_surface.commit.
//
// The blur algorithm is subject to compositor policies.
//
// If the associated surface has been destroyed, the surface_destroyed
// error will be raised.
//
//	region: blur region of the surface
func (i *ExtBackgroundEffectSurfaceV1) SetBlurRegion(region *client.Region) error {
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	if region == nil {
		client.PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		client.PutUint32(_reqBuf[l:l+4], region.ID())
		l += 4
	}
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type ExtBackgroundEffectSurfaceV1Error uint32

// ExtBackgroundEffectSurfaceV1Error :
const (
	// ExtBackgroundEffectSurfaceV1ErrorSurfaceDestroyed : the associated surface has been destroyed
	ExtBackgroundEffectSurfaceV1ErrorSurfaceDestroyed ExtBackgroundEffectSurfaceV1Error = 0
)

func (e ExtBackgroundEffectSurfaceV1Error) Name() string {
	switch e {
	case ExtBackgroundEffectSurfaceV1ErrorSurfaceDestroyed:
		return "surface_destroyed"
	default:
		return ""
	}
}

func (e ExtBackgroundEffectSurfaceV1Error) Value() string {
	switch e {
	case ExtBackgroundEffectSurfaceV1ErrorSurfaceDestroyed:
		return "0"
	default:
		return ""
	}
}

func (e ExtBackgroundEffectSurfaceV1Error) String() string {
	return e.Name() + "=" + e.Value()
}
