# generated by sysc-shell — do not edit
[colors.primary]
background = '{{.TerminalBackground}}'
foreground = '{{.TerminalForeground}}'

[colors.cursor]
text = '{{.TerminalCursorText}}'
cursor = '{{.TerminalCursor}}'

[colors.vi_mode_cursor]
text = '{{.Background}}'
cursor = '{{.Primary}}'

[colors.search.matches]
foreground = '{{.SurfaceVariant}}'
background = '{{.Tertiary}}'

[colors.search.focused_match]
foreground = '{{.SurfaceVariant}}'
background = '{{.Primary}}'

[colors.footer_bar]
foreground = '{{.SurfaceVariant}}'
background = '{{.InverseSurface}}'

[colors.hints.start]
foreground = '{{.SurfaceVariant}}'
background = '{{.Secondary}}'

[colors.hints.end]
foreground = '{{.SurfaceVariant}}'
background = '{{.Secondary}}'

[colors.selection]
text = '{{.TerminalSelectionForeground}}'
background = '{{.TerminalSelectionBackground}}'

[colors.normal]
black   = '{{.TerminalNormalBlack}}'
red     = '{{.TerminalNormalRed}}'
green   = '{{.TerminalNormalGreen}}'
yellow  = '{{.TerminalNormalYellow}}'
blue    = '{{.TerminalNormalBlue}}'
magenta = '{{.TerminalNormalMagenta}}'
cyan    = '{{.TerminalNormalCyan}}'
white   = '{{.TerminalNormalWhite}}'

[colors.bright]
black   = '{{.TerminalBrightBlack}}'
red     = '{{.TerminalBrightRed}}'
green   = '{{.TerminalBrightGreen}}'
yellow  = '{{.TerminalBrightYellow}}'
blue    = '{{.TerminalBrightBlue}}'
magenta = '{{.TerminalBrightMagenta}}'
cyan    = '{{.TerminalBrightCyan}}'
white   = '{{.TerminalBrightWhite}}'

[colors.dim]
black   = '{{.TerminalNormalBlack}}'
red     = '{{.TerminalNormalRed}}'
green   = '{{.TerminalNormalGreen}}'
yellow  = '{{.TerminalNormalYellow}}'
blue    = '{{.TerminalNormalBlue}}'
magenta = '{{.TerminalNormalMagenta}}'
cyan    = '{{.TerminalNormalCyan}}'
white   = '{{.TerminalNormalWhite}}'
