# generated by sysc-shell
[color]
foreground = '{{.Primary}}'

gradient = 1
gradient_color_1 = '{{.PrimaryContainer}}'
gradient_color_2 = '{{.Primary}}'
gradient_color_3 = '{{.OnPrimaryContainer}}'

horizontal_gradient = 0
horizontal_gradient_color_1 = '{{.PrimaryContainer}}'
horizontal_gradient_color_2 = '{{.Primary}}'
horizontal_gradient_color_3 = '{{.OnPrimaryContainer}}'
horizontal_gradient_color_4 = '{{.Primary}}'
horizontal_gradient_color_5 = '{{.PrimaryContainer}}'
