# generated by sysc-shell
# ponytail: foot wants bare rrggbb and [colors-dark]; Noctalia's exact shape.
[colors-dark]
foreground={{slice .TerminalForeground 1}}
background={{slice .TerminalBackground 1}}
regular0={{slice .TerminalNormalBlack 1}}
regular1={{slice .TerminalNormalRed 1}}
regular2={{slice .TerminalNormalGreen 1}}
regular3={{slice .TerminalNormalYellow 1}}
regular4={{slice .TerminalNormalBlue 1}}
regular5={{slice .TerminalNormalMagenta 1}}
regular6={{slice .TerminalNormalCyan 1}}
regular7={{slice .TerminalNormalWhite 1}}
bright0={{slice .TerminalBrightBlack 1}}
bright1={{slice .TerminalBrightRed 1}}
bright2={{slice .TerminalBrightGreen 1}}
bright3={{slice .TerminalBrightYellow 1}}
bright4={{slice .TerminalBrightBlue 1}}
bright5={{slice .TerminalBrightMagenta 1}}
bright6={{slice .TerminalBrightCyan 1}}
bright7={{slice .TerminalBrightWhite 1}}
selection-foreground={{slice .TerminalSelectionForeground 1}}
selection-background={{slice .TerminalSelectionBackground 1}}
cursor={{slice .TerminalCursorText 1}} {{slice .TerminalCursor 1}}
