# generated by sysc-shell
[KDE]
contrast=4

[General]
ColorScheme=sysc-shell
Name=sysc-shell

[ColorEffects:Disabled]
Color={{rgb .SurfaceContainerLowest}}
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
Color={{rgb .SurfaceVariant}}
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

[Colors:Button]
BackgroundAlternate={{rgb .SurfaceContainerLow}}
BackgroundNormal={{rgb .SurfaceContainerHigh}}
DecorationFocus={{rgb .Primary}}
DecorationHover={{rgb .Primary}}
ForegroundActive={{rgb .Primary}}
ForegroundInactive={{rgb .OnSurfaceVariant}}
ForegroundLink={{rgb .Secondary}}
ForegroundNegative={{rgb .Error}}
ForegroundNeutral={{rgb .Tertiary}}
ForegroundNormal={{rgb .OnSurface}}
ForegroundPositive={{rgb .Tertiary}}
ForegroundVisited={{rgb .OnSecondaryContainer}}

[Colors:Complementary]
BackgroundAlternate={{rgb .SurfaceContainerLow}}
BackgroundNormal={{rgb .Surface}}
DecorationFocus={{rgb .Primary}}
DecorationHover={{rgb .Primary}}
ForegroundActive={{rgb .Primary}}
ForegroundInactive={{rgb .OnSurfaceVariant}}
ForegroundLink={{rgb .Secondary}}
ForegroundNegative={{rgb .Error}}
ForegroundNeutral={{rgb .Tertiary}}
ForegroundNormal={{rgb .OnPrimaryContainer}}
ForegroundPositive={{rgb .Tertiary}}
ForegroundVisited={{rgb .OnSecondaryContainer}}

[Colors:Header]
BackgroundAlternate={{rgb .Surface}}
BackgroundNormal={{rgb .SurfaceContainer}}
DecorationFocus={{rgb .Primary}}
DecorationHover={{rgb .Primary}}
ForegroundActive={{rgb .Primary}}
ForegroundInactive={{rgb .OnSurfaceVariant}}
ForegroundLink={{rgb .Secondary}}
ForegroundNegative={{rgb .Error}}
ForegroundNeutral={{rgb .Tertiary}}
ForegroundNormal={{rgb .OnSurface}}
ForegroundPositive={{rgb .Tertiary}}
ForegroundVisited={{rgb .OnSecondaryContainer}}

[Colors:Header][Inactive]
BackgroundAlternate={{rgb .SurfaceContainer}}
BackgroundNormal={{rgb .Surface}}
DecorationFocus={{rgb .Primary}}
DecorationHover={{rgb .Primary}}
ForegroundActive={{rgb .Primary}}
ForegroundInactive={{rgb .OnSurfaceVariant}}
ForegroundLink={{rgb .Secondary}}
ForegroundNegative={{rgb .Error}}
ForegroundNeutral={{rgb .Tertiary}}
ForegroundNormal={{rgb .OnSurface}}
ForegroundPositive={{rgb .Tertiary}}
ForegroundVisited={{rgb .OnSecondaryContainer}}

[Colors:Selection]
BackgroundAlternate={{rgb .SurfaceContainerLow}}
BackgroundNormal={{rgb .Primary}}
DecorationFocus={{rgb .Primary}}
DecorationHover={{rgb .Primary}}
ForegroundActive={{rgb .OnPrimary}}
ForegroundInactive={{rgb .OnSurfaceVariant}}
ForegroundLink={{rgb .Secondary}}
ForegroundNegative={{rgb .ErrorContainer}}
ForegroundNeutral={{rgb .TertiaryContainer}}
ForegroundNormal={{rgb .OnPrimary}}
ForegroundPositive={{rgb .TertiaryContainer}}
ForegroundVisited={{rgb .OnSecondaryContainer}}

[Colors:Tooltip]
BackgroundAlternate={{rgb .Surface}}
BackgroundNormal={{rgb .SurfaceContainer}}
DecorationFocus={{rgb .Primary}}
DecorationHover={{rgb .Primary}}
ForegroundActive={{rgb .Primary}}
ForegroundInactive={{rgb .OnSurfaceVariant}}
ForegroundLink={{rgb .Secondary}}
ForegroundNegative={{rgb .Error}}
ForegroundNeutral={{rgb .Tertiary}}
ForegroundNormal={{rgb .OnBackground}}
ForegroundPositive={{rgb .Tertiary}}
ForegroundVisited={{rgb .OnSecondaryContainer}}

[Colors:View]
BackgroundAlternate={{rgb .SurfaceContainer}}
BackgroundNormal={{rgb .Background}}
DecorationFocus={{rgb .OnPrimaryContainer}}
DecorationHover={{rgb .OnPrimary}}
ForegroundActive={{rgb .Primary}}
ForegroundInactive={{rgb .OnSurfaceVariant}}
ForegroundLink={{rgb .Secondary}}
ForegroundNegative={{rgb .Error}}
ForegroundNeutral={{rgb .Tertiary}}
ForegroundNormal={{rgb .OnBackground}}
ForegroundPositive={{rgb .Tertiary}}
ForegroundVisited={{rgb .OnSecondaryContainer}}

[Colors:Window]
BackgroundAlternate={{rgb .PrimaryContainer}}
BackgroundNormal={{rgb .SurfaceContainer}}
DecorationFocus={{rgb .Primary}}
DecorationHover={{rgb .Primary}}
ForegroundActive={{rgb .Primary}}
ForegroundInactive={{rgb .OnSurfaceVariant}}
ForegroundLink={{rgb .Secondary}}
ForegroundNegative={{rgb .Error}}
ForegroundNeutral={{rgb .Tertiary}}
ForegroundNormal={{rgb .OnBackground}}
ForegroundPositive={{rgb .Tertiary}}
ForegroundVisited={{rgb .OnSecondaryContainer}}

[WM]
activeBackground={{rgb .PrimaryContainer}}
activeBlend={{rgb .OnPrimaryContainer}}
activeForeground={{rgb .OnPrimaryContainer}}
inactiveBackground={{rgb .Surface}}
inactiveBlend={{rgb .OnSurfaceVariant}}
inactiveForeground={{rgb .OnSurfaceVariant}}
