# generated by sysc-shell
color0 {{.TerminalNormalBlack}}
color1 {{.TerminalNormalRed}}
color2 {{.TerminalNormalGreen}}
color3 {{.TerminalNormalYellow}}
color4 {{.TerminalNormalBlue}}
color5 {{.TerminalNormalMagenta}}
color6 {{.TerminalNormalCyan}}
color7 {{.TerminalNormalWhite}}
color8 {{.TerminalBrightBlack}}
color9 {{.TerminalBrightRed}}
color10 {{.TerminalBrightGreen}}
color11 {{.TerminalBrightYellow}}
color12 {{.TerminalBrightBlue}}
color13 {{.TerminalBrightMagenta}}
color14 {{.TerminalBrightCyan}}
color15 {{.TerminalBrightWhite}}

cursor                {{.TerminalCursor}}
cursor_text_color     {{.TerminalCursorText}}
background            {{.TerminalBackground}}
foreground            {{.TerminalForeground}}
selection_foreground  {{.TerminalSelectionForeground}}
selection_background  {{.TerminalSelectionBackground}}
active_border_color   {{.Primary}}
inactive_border_color {{.SurfaceVariant}}
url_color             {{.Primary}}

active_tab_foreground   {{.OnPrimary}}
active_tab_background   {{.Primary}}
inactive_tab_foreground {{.OnSurfaceVariant}}
inactive_tab_background {{.SurfaceVariant}}
cursor_trail_color      {{.OnSurfaceVariant}}
