# generated by sysc-shell
set $primary            {{.Primary}}
set $on_primary         {{.OnPrimary}}
set $secondary          {{.Secondary}}
set $on_secondary_transp {{.OnSecondary}}AA
set $tertiary           {{.Tertiary}}
set $error              {{.Error}}
set $surface            {{.Surface}}
set $on_surface         {{.OnSurface}}
set $on_surface_variant {{.OnSurfaceVariant}}
set $outline            {{.Outline}}

## Window Colours
# class                 border    backgr.   text                indicator  child_border
client.focused          $primary  $surface  $on_surface         $primary   $primary
client.focused_inactive $outline  $surface  $on_surface_variant $outline   $outline
client.unfocused        $outline  $surface  $on_surface_variant $outline   $outline
client.urgent           $error    $surface  $on_surface         $error     $error
client.placeholder      $surface  $surface  $on_surface_variant $surface   $surface
client.background       $surface

jump_labels_color       $secondary
jump_labels_background  $on_secondary_transp
