# generated by sysc-shell
[colors]
ansi = [
    "{{.TerminalNormalBlack}}",
    "{{.TerminalNormalRed}}",
    "{{.TerminalNormalGreen}}",
    "{{.TerminalNormalYellow}}",
    "{{.TerminalNormalBlue}}",
    "{{.TerminalNormalMagenta}}",
    "{{.TerminalNormalCyan}}",
    "{{.TerminalNormalWhite}}",
]
background = "{{.TerminalBackground}}"
brights = [
    "{{.TerminalBrightBlack}}",
    "{{.TerminalBrightRed}}",
    "{{.TerminalBrightGreen}}",
    "{{.TerminalBrightYellow}}",
    "{{.TerminalBrightBlue}}",
    "{{.TerminalBrightMagenta}}",
    "{{.TerminalBrightCyan}}",
    "{{.TerminalBrightWhite}}",
]
compose_cursor = "{{.TerminalCursor}}"
cursor_bg = "{{.TerminalCursor}}"
cursor_border = "{{.TerminalCursor}}"
cursor_fg = "{{.TerminalCursorText}}"
foreground = "{{.TerminalForeground}}"
scrollbar_thumb = "{{.TerminalSelectionBackground}}"
selection_bg = "{{.TerminalSelectionBackground}}"
selection_fg = "{{.TerminalSelectionForeground}}"
split = "{{.TerminalBrightBlack}}"
visual_bell = "{{.TerminalNormalBlack}}"

[colors.indexed]
16 = "{{.Secondary}}"
17 = "{{.TerminalCursor}}"

[colors.tab_bar]
background = "{{darken .TerminalBackground 0.1}}"
inactive_tab_edge = "{{.TerminalSelectionBackground}}"

[colors.tab_bar.active_tab]
bg_color = "{{.Primary}}"
fg_color = "{{.OnPrimary}}"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "{{darken .TerminalBackground 0.05}}"
fg_color = "{{.TerminalForeground}}"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "{{.TerminalBackground}}"
fg_color = "{{.TerminalForeground}}"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "{{.TerminalSelectionBackground}}"
fg_color = "{{.TerminalForeground}}"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "{{.TerminalBrightBlack}}"
fg_color = "{{.TerminalForeground}}"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[metadata]
author = "sysc-shell"
name = "sysc-shell"
