package theming

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestApplyWriteAdoptsOnlyWhatItRendered(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_STATE_HOME", dir)
	p := filepath.Join(dir, "foot.ini")
	rendered := "# generated by sysc-shell — do not edit\nok\n"

	if err := ApplyWrite(p, rendered); err != nil {
		t.Fatalf("absent target: %v", err)
	}
	if err := ApplyWrite(p, rendered+"\n"); err != nil {
		t.Fatalf("untouched target: %v", err)
	}
	if err := os.WriteFile(p, []byte("user edit\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := ApplyWrite(p, rendered); !errors.Is(err, ErrUserModified) {
		t.Fatalf("edited target: %v, want ErrUserModified", err)
	}
	if got, _ := os.ReadFile(p); string(got) != "user edit\n" {
		t.Fatalf("refused target was modified: %q", got)
	}

	orphan := filepath.Join(dir, "kitty.conf")
	if err := os.WriteFile(orphan, []byte(rendered), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := ApplyWrite(orphan, rendered); !errors.Is(err, ErrUserModified) {
		t.Fatalf("unrecorded target: %v, want ErrUserModified", err)
	}

	empty := filepath.Join(dir, "empty.conf")
	if err := os.WriteFile(empty, nil, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := ApplyWrite(empty, rendered); err != nil {
		t.Fatalf("empty target: %v", err)
	}

	entries, _ := os.ReadDir(dir)
	for _, e := range entries {
		if strings.HasPrefix(e.Name(), ".sysc-") {
			t.Fatalf("temp file %s left behind", e.Name())
		}
	}
}

func TestApplyWriteForceBacksUpAndReadopts(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_STATE_HOME", dir)
	p := filepath.Join(dir, "foot.ini")
	if err := os.WriteFile(p, []byte("user edit\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	rendered := "# generated by sysc-shell — do not edit\nok\n"
	if err := ApplyWriteForce(p, rendered); err != nil {
		t.Fatal(err)
	}
	if got, _ := os.ReadFile(p); string(got) != rendered {
		t.Fatalf("force did not write: %q", got)
	}
	if got, _ := os.ReadFile(p + ".bak"); string(got) != "user edit\n" {
		t.Fatalf("backup = %q", got)
	}
	if err := ApplyWrite(p, rendered+"\n"); err != nil {
		t.Fatalf("a forced write was not adopted: %v", err)
	}
	// A second overwrite must not destroy the first backup.
	if err := os.WriteFile(p, []byte("more user edits\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := ApplyWriteForce(p, rendered); err != nil {
		t.Fatal(err)
	}
	if got, _ := os.ReadFile(p + ".bak"); string(got) != "user edit\n" {
		t.Fatalf("second force clobbered the backup: %q", got)
	}
}

func TestApplyWriteSurvivesANullStateRecord(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_STATE_HOME", dir)
	state := filepath.Join(dir, "sysc-shell", "templates", "state.json")
	if err := os.MkdirAll(filepath.Dir(state), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(state, []byte("null"), 0o644); err != nil {
		t.Fatal(err)
	}
	p := filepath.Join(dir, "foot.ini")
	if err := ApplyWrite(p, "# generated by sysc-shell — do not edit\nok\n"); err != nil {
		t.Fatalf("null state record: %v", err)
	}
}

func TestApplyWriteRefusesAReadOnlyTarget(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_STATE_HOME", dir)
	p := filepath.Join(dir, "foot.ini")
	rendered := "# generated by sysc-shell — do not edit\nok\n"
	if err := ApplyWrite(p, rendered); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(p, 0o444); err != nil {
		t.Fatal(err)
	}
	defer os.Chmod(p, 0o644)
	if err := ApplyWrite(p, rendered+"\n"); err == nil {
		t.Fatal("a read-only target must report the failure, not be renamed over")
	}
	if got, _ := os.ReadFile(p); string(got) != rendered {
		t.Fatalf("read-only target changed: %q", got)
	}
}

func TestApplyPlainWriteNeverOverwritesForeignContent(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	p := filepath.Join(t.TempDir(), "alacritty.toml")
	if err := os.WriteFile(p, []byte("user stuff\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := ApplyWrite(p, "# generated by sysc-shell — do not edit\nok\n"); err == nil {
		t.Fatal("must skip foreign content")
	}
	got, _ := os.ReadFile(p)
	if string(got) != "user stuff\n" {
		t.Fatalf("rewrote user file: %q", got)
	}
}

func TestNiriIncludeInjectionIdempotent(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	dir := t.TempDir()
	cfg := filepath.Join(dir, "config.kdl")
	gen := filepath.Join(dir, "sysc-shell.kdl")
	if err := os.WriteFile(cfg, []byte("keybinds { }\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	rendered := "// generated by sysc-shell — do not edit\nlayout {}\n"
	if err := ApplyNiri(cfg, gen, rendered); err != nil {
		t.Fatal(err)
	}
	if err := ApplyNiri(cfg, gen, rendered); err != nil {
		t.Fatal(err)
	}
	content, _ := os.ReadFile(cfg)
	if strings.Count(string(content), niriInclude) != 1 {
		t.Fatalf("include count in %q", content)
	}
}

func TestGtkThemeNameOnlySwitchedWhenUnsetOrOurs(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	adw := filepath.Join(dir, "adw.ini")
	if err := os.WriteFile(adw, []byte("[Settings]\ngtk-theme-name=Adwaita\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := ApplyGtkThemeName(adw, gtkOurs); err != nil {
		t.Fatal(err)
	}
	got, _ := os.ReadFile(adw)
	if !strings.Contains(string(got), "Adwaita") {
		t.Fatal("Adwaita was replaced")
	}

	ours := filepath.Join(dir, "ours.ini")
	if err := os.WriteFile(ours, []byte("[Settings]\ngtk-theme-name=sysc-shell-Dark\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := ApplyGtkThemeName(ours, "sysc-shell-Light"); err != nil {
		t.Fatal(err)
	}
	got, _ = os.ReadFile(ours)
	if !strings.Contains(string(got), "sysc-shell-Light") {
		t.Fatalf("ours theme not updated: %s", got)
	}

	absent := filepath.Join(dir, "absent.ini")
	if err := ApplyGtkThemeName(absent, gtkOurs); err != nil {
		t.Fatal(err)
	}
	got, _ = os.ReadFile(absent)
	if !strings.Contains(string(got), "gtk-theme-name="+gtkOurs) {
		t.Fatalf("absent not set: %s", got)
	}
}

func TestDisablingNiriTemplateRemovesIncludeAndFile(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	dir := t.TempDir()
	cfg := filepath.Join(dir, "config.kdl")
	gen := filepath.Join(dir, "sysc-shell.kdl")
	if err := os.WriteFile(cfg, []byte("keybinds { }\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := ApplyNiri(cfg, gen, "// generated by sysc-shell — do not edit\n"); err != nil {
		t.Fatal(err)
	}
	if err := UnapplyNiri(cfg, gen); err != nil {
		t.Fatal(err)
	}
	content, _ := os.ReadFile(cfg)
	if strings.Contains(string(content), niriInclude) {
		t.Fatal("include line survived disable")
	}
	if !strings.Contains(string(content), "keybinds") {
		t.Fatal("disable damaged user content")
	}
	if _, err := os.Stat(gen); !os.IsNotExist(err) {
		t.Fatal("generated kdl survived disable")
	}
}

func TestDisableIsIdempotentAndSafeWhenNeverApplied(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	cfg := filepath.Join(dir, "config.kdl")
	gen := filepath.Join(dir, "sysc-shell.kdl")
	if err := os.WriteFile(cfg, []byte("keybinds { }\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := UnapplyNiri(cfg, gen); err != nil {
		t.Fatal(err)
	}
	if err := UnapplyNiri(cfg, gen); err != nil {
		t.Fatal(err)
	}
	got, _ := os.ReadFile(cfg)
	if string(got) != "keybinds { }\n" {
		t.Fatal("disable modified a config it never touched")
	}
}

func TestDisableGtkRestoresOnlyOurThemeName(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	ours := filepath.Join(dir, "ours.ini")
	if err := os.WriteFile(ours, []byte("[Settings]\ngtk-theme-name=sysc-shell-Dark\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := UnapplyGtkThemeName(ours); err != nil {
		t.Fatal(err)
	}
	got, _ := os.ReadFile(ours)
	if strings.Contains(string(got), "gtk-theme-name=sysc-shell-Dark") {
		t.Fatalf("ours name survived: %s", got)
	}

	adw := filepath.Join(dir, "adw.ini")
	if err := os.WriteFile(adw, []byte("[Settings]\ngtk-theme-name=Adwaita\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := UnapplyGtkThemeName(adw); err != nil {
		t.Fatal(err)
	}
	got, _ = os.ReadFile(adw)
	if !strings.Contains(string(got), "Adwaita") {
		t.Fatal("Adwaita was touched")
	}
}

func TestReadOnlyNiriConfigIsReportedNotRewritten(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	dir := t.TempDir()
	cfg := filepath.Join(dir, "config.kdl")
	gen := filepath.Join(dir, "sysc-shell.kdl")
	if err := os.WriteFile(cfg, []byte("keybinds { }\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(cfg, 0o444); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(cfg, 0o644) })
	if err := ApplyNiri(cfg, gen, "// generated by sysc-shell — do not edit\n"); err == nil {
		t.Fatal("read-only config must report failure")
	}
	got, _ := os.ReadFile(cfg)
	if string(got) != "keybinds { }\n" {
		t.Fatal("read-only config was modified")
	}
}

func TestThemingWritesLeaveNoTempFiles(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	dir := t.TempDir()
	cfg := filepath.Join(dir, "config.kdl")
	gen := filepath.Join(dir, "sysc-shell.kdl")
	ini := filepath.Join(dir, "settings.ini")
	for _, p := range []string{cfg, ini} {
		if err := os.WriteFile(p, []byte("[Settings]\ngtk-theme-name=sysc-shell-Old\n"), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	rendered := "// generated by sysc-shell — do not edit\nlayout {}\n"
	for _, op := range []func() error{
		func() error { return ApplyWrite(gen, rendered) },
		func() error { return ApplyNiri(cfg, gen, rendered) },
		func() error { return UnapplyNiri(cfg, gen) },
		func() error { return ApplyGtkThemeName(ini, "sysc-shell-New") },
		func() error { return UnapplyGtkThemeName(ini) },
	} {
		if err := op(); err != nil {
			t.Fatal(err)
		}
		entries, err := os.ReadDir(dir)
		if err != nil {
			t.Fatal(err)
		}
		for _, e := range entries {
			if strings.Contains(e.Name(), ".sysc-") {
				t.Fatalf("atomic write leaked %s", e.Name())
			}
		}
	}
	if content, err := os.ReadFile(gen); err == nil && !strings.Contains(string(content), "layout") {
		t.Fatalf("atomic replace lost content: %q", content)
	} // UnapplyNiri deletes gen, so absence is the expected final state.
}
