package theming

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestApplyPlainWriteNeverOverwritesForeignContent(t *testing.T) {
	t.Parallel()
	p := filepath.Join(t.TempDir(), "alacritty.toml")
	if err := os.WriteFile(p, []byte("user stuff\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := ApplyWrite(p, "# generated by sysc-shell — do not edit\nok\n"); err == nil {
		t.Fatal("must skip foreign content")
	}
	got, _ := os.ReadFile(p)
	if string(got) != "user stuff\n" {
		t.Fatalf("rewrote user file: %q", got)
	}
}

func TestNiriIncludeInjectionIdempotent(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	cfg := filepath.Join(dir, "config.kdl")
	gen := filepath.Join(dir, "sysc-shell.kdl")
	if err := os.WriteFile(cfg, []byte("keybinds { }\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	rendered := "// generated by sysc-shell — do not edit\nlayout {}\n"
	if err := ApplyNiri(cfg, gen, rendered); err != nil {
		t.Fatal(err)
	}
	if err := ApplyNiri(cfg, gen, rendered); err != nil {
		t.Fatal(err)
	}
	content, _ := os.ReadFile(cfg)
	if strings.Count(string(content), niriInclude) != 1 {
		t.Fatalf("include count in %q", content)
	}
}

func TestGtkThemeNameOnlySwitchedWhenUnsetOrOurs(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	adw := filepath.Join(dir, "adw.ini")
	if err := os.WriteFile(adw, []byte("[Settings]\ngtk-theme-name=Adwaita\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := ApplyGtkThemeName(adw, gtkOurs); err != nil {
		t.Fatal(err)
	}
	got, _ := os.ReadFile(adw)
	if !strings.Contains(string(got), "Adwaita") {
		t.Fatal("Adwaita was replaced")
	}

	ours := filepath.Join(dir, "ours.ini")
	if err := os.WriteFile(ours, []byte("[Settings]\ngtk-theme-name=sysc-shell-Dark\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := ApplyGtkThemeName(ours, "sysc-shell-Light"); err != nil {
		t.Fatal(err)
	}
	got, _ = os.ReadFile(ours)
	if !strings.Contains(string(got), "sysc-shell-Light") {
		t.Fatalf("ours theme not updated: %s", got)
	}

	absent := filepath.Join(dir, "absent.ini")
	if err := ApplyGtkThemeName(absent, gtkOurs); err != nil {
		t.Fatal(err)
	}
	got, _ = os.ReadFile(absent)
	if !strings.Contains(string(got), "gtk-theme-name="+gtkOurs) {
		t.Fatalf("absent not set: %s", got)
	}
}

func TestDisablingNiriTemplateRemovesIncludeAndFile(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	cfg := filepath.Join(dir, "config.kdl")
	gen := filepath.Join(dir, "sysc-shell.kdl")
	if err := os.WriteFile(cfg, []byte("keybinds { }\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := ApplyNiri(cfg, gen, "// generated by sysc-shell — do not edit\n"); err != nil {
		t.Fatal(err)
	}
	if err := UnapplyNiri(cfg, gen); err != nil {
		t.Fatal(err)
	}
	content, _ := os.ReadFile(cfg)
	if strings.Contains(string(content), niriInclude) {
		t.Fatal("include line survived disable")
	}
	if !strings.Contains(string(content), "keybinds") {
		t.Fatal("disable damaged user content")
	}
	if _, err := os.Stat(gen); !os.IsNotExist(err) {
		t.Fatal("generated kdl survived disable")
	}
}

func TestDisableIsIdempotentAndSafeWhenNeverApplied(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	cfg := filepath.Join(dir, "config.kdl")
	gen := filepath.Join(dir, "sysc-shell.kdl")
	if err := os.WriteFile(cfg, []byte("keybinds { }\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := UnapplyNiri(cfg, gen); err != nil {
		t.Fatal(err)
	}
	if err := UnapplyNiri(cfg, gen); err != nil {
		t.Fatal(err)
	}
	got, _ := os.ReadFile(cfg)
	if string(got) != "keybinds { }\n" {
		t.Fatal("disable modified a config it never touched")
	}
}

func TestDisableGtkRestoresOnlyOurThemeName(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	ours := filepath.Join(dir, "ours.ini")
	if err := os.WriteFile(ours, []byte("[Settings]\ngtk-theme-name=sysc-shell-Dark\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := UnapplyGtkThemeName(ours); err != nil {
		t.Fatal(err)
	}
	got, _ := os.ReadFile(ours)
	if strings.Contains(string(got), "gtk-theme-name=sysc-shell-Dark") {
		t.Fatalf("ours name survived: %s", got)
	}

	adw := filepath.Join(dir, "adw.ini")
	if err := os.WriteFile(adw, []byte("[Settings]\ngtk-theme-name=Adwaita\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := UnapplyGtkThemeName(adw); err != nil {
		t.Fatal(err)
	}
	got, _ = os.ReadFile(adw)
	if !strings.Contains(string(got), "Adwaita") {
		t.Fatal("Adwaita was touched")
	}
}

func TestReadOnlyNiriConfigIsReportedNotRewritten(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	cfg := filepath.Join(dir, "config.kdl")
	gen := filepath.Join(dir, "sysc-shell.kdl")
	if err := os.WriteFile(cfg, []byte("keybinds { }\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(cfg, 0o444); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(cfg, 0o644) })
	if err := ApplyNiri(cfg, gen, "// generated by sysc-shell — do not edit\n"); err == nil {
		t.Fatal("read-only config must report failure")
	}
	got, _ := os.ReadFile(cfg)
	if string(got) != "keybinds { }\n" {
		t.Fatal("read-only config was modified")
	}
}

func TestThemingWritesLeaveNoTempFiles(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	cfg := filepath.Join(dir, "config.kdl")
	gen := filepath.Join(dir, "sysc-shell.kdl")
	ini := filepath.Join(dir, "settings.ini")
	for _, p := range []string{cfg, ini} {
		if err := os.WriteFile(p, []byte("[Settings]\ngtk-theme-name=sysc-shell-Old\n"), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	rendered := "// generated by sysc-shell — do not edit\nlayout {}\n"
	for _, op := range []func() error{
		func() error { return ApplyWrite(gen, rendered) },
		func() error { return ApplyNiri(cfg, gen, rendered) },
		func() error { return UnapplyNiri(cfg, gen) },
		func() error { return ApplyGtkThemeName(ini, "sysc-shell-New") },
		func() error { return UnapplyGtkThemeName(ini) },
	} {
		if err := op(); err != nil {
			t.Fatal(err)
		}
		entries, err := os.ReadDir(dir)
		if err != nil {
			t.Fatal(err)
		}
		for _, e := range entries {
			if strings.Contains(e.Name(), ".sysc-") {
				t.Fatalf("atomic write leaked %s", e.Name())
			}
		}
	}
	if content, err := os.ReadFile(gen); err == nil && !strings.Contains(string(content), "layout") {
		t.Fatalf("atomic replace lost content: %q", content)
	} // UnapplyNiri deletes gen, so absence is the expected final state.
}
