package theming

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	marker      = "generated by sysc-shell"
	niriInclude = `include "sysc-shell.kdl"`
	gtkOurs     = "sysc-shell-Dark"
)

func oursFile(content string) bool {
	line, _, _ := strings.Cut(content, "\n")
	return strings.Contains(line, marker)
}

// ApplyWrite writes rendered content when the target is missing or already ours.
func ApplyWrite(path, rendered string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if b, err := os.ReadFile(path); err == nil && !oursFile(string(b)) {
		return fmt.Errorf("skipped: user file")
	}
	return os.WriteFile(path, []byte(rendered), 0o644)
}

func UnapplyWrite(path string) error {
	b, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if !oursFile(string(b)) {
		return nil
	}
	return os.Remove(path)
}

func ApplyNiri(configPath, genPath, rendered string) error {
	if err := ApplyWrite(genPath, rendered); err != nil {
		return err
	}
	b, err := os.ReadFile(configPath)
	if err != nil {
		return err
	}
	body := string(b)
	if strings.Contains(body, niriInclude) {
		return nil
	}
	out := body
	if !strings.HasSuffix(out, "\n") && out != "" {
		out += "\n"
	}
	out += niriInclude + "\n"
	return os.WriteFile(configPath, []byte(out), 0o644)
}

func UnapplyNiri(configPath, genPath string) error {
	if err := UnapplyWrite(genPath); err != nil {
		return err
	}
	b, err := os.ReadFile(configPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	lines := strings.SplitAfter(string(b), "\n")
	var keep []string
	for _, ln := range lines {
		if strings.TrimSpace(ln) == niriInclude {
			continue
		}
		keep = append(keep, ln)
	}
	return os.WriteFile(configPath, []byte(strings.Join(keep, "")), 0o644)
}

func ApplyGtkThemeName(iniPath, name string) error {
	if name == "" {
		name = gtkOurs
	}
	b, err := os.ReadFile(iniPath)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	body := string(b)
	if cur, ok := gtkThemeName(body); ok && !strings.HasPrefix(cur, "sysc-shell-") {
		return nil
	}
	return writeGtkThemeName(iniPath, body, name)
}

func UnapplyGtkThemeName(iniPath string) error {
	b, err := os.ReadFile(iniPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	body := string(b)
	cur, ok := gtkThemeName(body)
	if !ok || !strings.HasPrefix(cur, "sysc-shell-") {
		return nil
	}
	return writeGtkThemeName(iniPath, body, "")
}

func gtkThemeName(body string) (string, bool) {
	for _, ln := range strings.Split(body, "\n") {
		ln = strings.TrimSpace(ln)
		if k, v, ok := strings.Cut(ln, "="); ok && strings.TrimSpace(k) == "gtk-theme-name" {
			return strings.TrimSpace(v), true
		}
	}
	return "", false
}

func writeGtkThemeName(path, body, name string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	lines := strings.Split(body, "\n")
	found := false
	for i, ln := range lines {
		trim := strings.TrimSpace(ln)
		if k, _, ok := strings.Cut(trim, "="); ok && strings.TrimSpace(k) == "gtk-theme-name" {
			found = true
			if name == "" {
				lines[i] = ""
			} else {
				lines[i] = "gtk-theme-name=" + name
			}
		}
	}
	out := strings.Join(lines, "\n")
	if !found && name != "" {
		if body != "" && !strings.HasSuffix(body, "\n") {
			out += "\n"
		}
		if !strings.Contains(out, "[Settings]") {
			out += "[Settings]\n"
		}
		out += "gtk-theme-name=" + name + "\n"
	}
	return os.WriteFile(path, []byte(out), 0o644)
}
