package theming

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	marker      = "generated by sysc-shell"
	niriInclude = `include "sysc-shell.kdl"`
	gtkOurs     = "sysc-shell-Dark"
)

func oursFile(content string) bool {
	line, _, _ := strings.Cut(content, "\n")
	return strings.Contains(line, marker)
}

// ErrUserModified reports a target whose current bytes the shell cannot
// account for: the user edited it, or the shell has no record of ever writing
// it. The settings Templates surface offers an explicit overwrite.
var ErrUserModified = errors.New("theming: target modified outside the shell")

// ApplyWrite writes rendered content over a target the shell can account for:
// absent, empty, or byte-identical to what it last rendered. Anything else is
// refused rather than clobbered.
func ApplyWrite(path, rendered string) error {
	return applyWrite(path, rendered, false)
}

func applyWrite(path, rendered string, force bool) error {
	if force {
		return applyWriteForce(path, rendered)
	}
	if current, err := os.ReadFile(path); err == nil && len(bytes.TrimSpace(current)) > 0 {
		if stateHash(path) != hash(current) {
			return fmt.Errorf("%w: %s", ErrUserModified, path)
		}
	} else if err != nil && !os.IsNotExist(err) {
		return err
	}
	return writeAdopted(path, []byte(rendered))
}

// ApplyWriteForce overwrites regardless of the target's history, backing the
// previous bytes up to <path>.bak first. It is the explicit action behind a
// refusal, never a default.
func ApplyWriteForce(path, rendered string) error {
	return applyWriteForce(path, rendered)
}

func applyWriteForce(path, rendered string) error {
	if info, err := os.Stat(path); err == nil && info.Size() > 0 {
		if err := os.Rename(path, path+".bak"); err != nil {
			return err
		}
	}
	return writeAdopted(path, []byte(rendered))
}

func writeAdopted(path string, data []byte) error {
	if err := swapWrite(path, data); err != nil {
		return err
	}
	// The state file is a cache, never an authority: failing to record here
	// degrades the next apply to a refusal, which is the safe direction.
	_ = rememberHash(path, hash(data))
	return nil
}

// swapWrite renders into a sibling temp file and renames it over the target.
// Rename is atomic within a directory, so a reader never sees a half-written
// config and a crash leaves the previous bytes in place.
func swapWrite(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".sysc-*")
	if err != nil {
		return err
	}
	name := tmp.Name()
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		os.Remove(name)
		return err
	}
	if err := tmp.Close(); err != nil {
		os.Remove(name)
		return err
	}
	if err := os.Chmod(name, 0o644); err != nil {
		os.Remove(name)
		return err
	}
	return os.Rename(name, path)
}

// statePath is $XDG_STATE_HOME/sysc-shell/templates/state.json. The design
// says XDG_STATE_HOME/sysc/; every state root in this repository is
// sysc-shell (internal/wallpaper/persist.go:41, internal/plugin/state.go:54),
// so the record follows the convention.
func statePath() string {
	base := os.Getenv("XDG_STATE_HOME")
	if base == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return ""
		}
		base = filepath.Join(home, ".local", "state")
	}
	return filepath.Join(base, "sysc-shell", "templates", "state.json")
}

// loadState reads the rendered-hash record. Any problem -- absent, corrupt,
// unwritable -- is an empty record: losing the state file must degrade to
// refusing, never to clobbering.
func loadState() map[string]string {
	state := map[string]string{}
	if data, err := os.ReadFile(statePath()); err == nil {
		_ = json.Unmarshal(data, &state)
	}
	return state
}

func stateHash(path string) string { return loadState()[path] }

func rememberHash(path, sum string) error {
	root := statePath()
	if root == "" {
		return nil
	}
	state := loadState()
	state[path] = sum
	data, err := json.Marshal(state)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(root), 0o755); err != nil {
		return err
	}
	return os.WriteFile(root, data, 0o644)
}

func hash(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

func UnapplyWrite(path string) error {
	b, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if !oursFile(string(b)) {
		return nil
	}
	return os.Remove(path)
}

func ApplyNiri(configPath, genPath, rendered string) error {
	return applyNiri(configPath, genPath, rendered, false)
}

func applyNiri(configPath, genPath, rendered string, force bool) error {
	if err := applyWrite(genPath, rendered, force); err != nil {
		return err
	}
	b, err := os.ReadFile(configPath)
	if err != nil {
		return err
	}
	body := string(b)
	if strings.Contains(body, niriInclude) {
		return nil
	}
	out := body
	if !strings.HasSuffix(out, "\n") && out != "" {
		out += "\n"
	}
	out += niriInclude + "\n"
	return writeFileAtomic(configPath, []byte(out), 0o644)
}

func UnapplyNiri(configPath, genPath string) error {
	if err := UnapplyWrite(genPath); err != nil {
		return err
	}
	b, err := os.ReadFile(configPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	lines := strings.SplitAfter(string(b), "\n")
	var keep []string
	for _, ln := range lines {
		if strings.TrimSpace(ln) == niriInclude {
			continue
		}
		keep = append(keep, ln)
	}
	return writeFileAtomic(configPath, []byte(strings.Join(keep, "")), 0o644)
}

func ApplyGtkThemeName(iniPath, name string) error {
	if name == "" {
		name = gtkOurs
	}
	b, err := os.ReadFile(iniPath)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	body := string(b)
	if cur, ok := gtkThemeName(body); ok && !strings.HasPrefix(cur, "sysc-shell-") {
		return nil
	}
	return writeGtkThemeName(iniPath, body, name)
}

func UnapplyGtkThemeName(iniPath string) error {
	b, err := os.ReadFile(iniPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	body := string(b)
	cur, ok := gtkThemeName(body)
	if !ok || !strings.HasPrefix(cur, "sysc-shell-") {
		return nil
	}
	return writeGtkThemeName(iniPath, body, "")
}

func gtkThemeName(body string) (string, bool) {
	for _, ln := range strings.Split(body, "\n") {
		ln = strings.TrimSpace(ln)
		if k, v, ok := strings.Cut(ln, "="); ok && strings.TrimSpace(k) == "gtk-theme-name" {
			return strings.TrimSpace(v), true
		}
	}
	return "", false
}

func writeGtkThemeName(path, body, name string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	lines := strings.Split(body, "\n")
	found := false
	for i, ln := range lines {
		trim := strings.TrimSpace(ln)
		if k, _, ok := strings.Cut(trim, "="); ok && strings.TrimSpace(k) == "gtk-theme-name" {
			found = true
			if name == "" {
				lines[i] = ""
			} else {
				lines[i] = "gtk-theme-name=" + name
			}
		}
	}
	out := strings.Join(lines, "\n")
	if !found && name != "" {
		if body != "" && !strings.HasSuffix(body, "\n") {
			out += "\n"
		}
		if !strings.Contains(out, "[Settings]") {
			out += "[Settings]\n"
		}
		out += "gtk-theme-name=" + name + "\n"
	}
	return writeFileAtomic(path, []byte(out), 0o644)
}

// writeFileAtomic replaces path via a unique temp in the same directory, then
// rename, so a reader (niri watching its config, a GTK app loading settings)
// never sees a half-written file and a crash leaves the previous content
// intact (GitHub #23; same shape as config.Write, without its symlink
// guarantee).
func writeFileAtomic(path string, data []byte, mode os.FileMode) error {
	// A rename would replace an unwritable target that a direct write must
	// fail on; keep reporting read-only files instead of silently succeeding.
	if f, err := os.OpenFile(path, os.O_WRONLY, 0); err != nil {
		if !errors.Is(err, os.ErrNotExist) {
			return err
		}
	} else {
		_ = f.Close()
	}
	f, err := os.CreateTemp(filepath.Dir(path), ".sysc-*.tmp")
	if err != nil {
		return err
	}
	tmp := f.Name()
	defer os.Remove(tmp)
	if err := f.Chmod(mode); err != nil {
		_ = f.Close()
		return err
	}
	if _, err := f.Write(data); err != nil {
		_ = f.Close()
		return err
	}
	if err := f.Sync(); err != nil {
		_ = f.Close()
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
