package theming

import (
	"errors"
	"os"
	"os/signal"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"testing"
	"time"

	"github.com/Nomadcxx/sysc-shell/internal/theme"
)

func applyForTest(home string, enabled func(string) bool, tok theme.Tokens) error {
	_, _, err := ApplyEnabled(home, enabled, tok, 100)
	return err
}

// markTemplatesComplete lets mechanism tests exercise the write path of a
// template the release has not verified yet (GH #7 gate).
func markTemplatesComplete(t *testing.T, names ...string) {
	t.Helper()
	for _, n := range names {
		if !completeTemplates[n] {
			completeTemplates[n] = true
			t.Cleanup(func() { delete(completeTemplates, n) })
		}
	}
}

func TestApplyEnabledReportsRefusalsPerTemplate(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	home := t.TempDir()
	markTemplatesComplete(t, "cava")
	target := filepath.Join(home, ".config", "cava", "config")
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(target, []byte("[color]\ntheme = user-choice\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	only := func(name string) bool { return name == "cava" }
	// An enabled template is applied over the user's own value (owner
	// decision, 2026-10-09), and the takeover is reported.
	outcomes, adopted, err := ApplyEnabled(home, only, theme.Fallback, 100)
	if err != nil || len(outcomes) != 0 {
		t.Fatalf("apply = %v, %v; want the template adopted", outcomes, err)
	}
	if !slices.Equal(adopted, []string{"cava"}) {
		t.Fatalf("adopted = %v, want cava", adopted)
	}
	if backup, _ := os.ReadFile(target + ".bak"); string(backup) != "[color]\ntheme = user-choice\n" {
		t.Fatalf("backup = %q, want the user's file", backup)
	}
	// Once the shell owns the setting, a re-apply adopts nothing.
	if _, again, err := ApplyEnabled(home, only, theme.Fallback, 100); err != nil || len(again) != 0 {
		t.Fatalf("re-apply adopted %v, err %v", again, err)
	}
	if got, _ := os.ReadFile(target); string(got) != "[color]\ntheme = \"sysc-shell\"\n" {
		t.Fatalf("forced directive replacement = %q", got)
	}
	if backup, err := os.ReadFile(target + ".bak"); err != nil || string(backup) != "[color]\ntheme = user-choice\n" {
		t.Fatalf("refused config backup = %q, %v", backup, err)
	}
}

func TestApplyEnabledWritesAlacrittyUnderXDG(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	home := t.TempDir()
	markTemplatesComplete(t, "alacritty")
	only := func(name string) bool { return name == "alacritty" }
	if _, _, err := ApplyEnabled(home, only, theme.Fallback, 100); err != nil {
		t.Fatal(err)
	}
	sidecar := filepath.Join(home, ".config", "alacritty", "themes", "sysc-shell.toml")
	b, err := os.ReadFile(sidecar)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(b), marker) {
		t.Fatalf("missing marker in %s", sidecar)
	}
	cfg, err := os.ReadFile(filepath.Join(home, ".config", "alacritty", "alacritty.toml"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(cfg), `import = ["`+sidecar+`"]`) {
		t.Fatalf("import directive missing: %q", cfg)
	}
}

func TestDisablePreservesSidecarReferencedByAnUnownedDirective(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	home := t.TempDir()
	target := templateTargets["foot"]
	directive := target.directives(home)[0]
	sidecar := target.sidecar(home)[0]
	if err := os.MkdirAll(filepath.Dir(directive.file), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(directive.file, []byte(directive.line+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := ApplySidecar(sidecar, "# generated by sysc-shell\n"); err != nil {
		t.Fatal(err)
	}

	if err := applyTemplateTarget("foot", home, false, "", false, 100); !errors.Is(err, ErrUserModified) {
		t.Fatalf("disable with unowned directive = %v, want ErrUserModified", err)
	}
	if got, err := os.ReadFile(sidecar); err != nil || string(got) != "# generated by sysc-shell\n" {
		t.Fatalf("referenced sidecar = %q, %v", got, err)
	}
}

func TestDisablePreservesSidecarAfterDirectiveEdit(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	home := t.TempDir()
	target := templateTargets["foot"]
	directive := target.directives(home)[0]
	sidecar := target.sidecar(home)[0]
	if err := os.MkdirAll(filepath.Dir(directive.file), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(directive.file, []byte("font-size=12\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := EnsureDirective(directive); err != nil {
		t.Fatal(err)
	}
	if err := ApplySidecar(sidecar, "# generated by sysc-shell\n"); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(directive.file, []byte("font-size=12\ninclude=~/.config/foot/themes/user-choice\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := applyTemplateTarget("foot", home, false, "", false, 100); !errors.Is(err, ErrUserModified) {
		t.Fatalf("disable with edited directive = %v, want ErrUserModified", err)
	}
	if got, err := os.ReadFile(sidecar); err != nil || string(got) != "# generated by sysc-shell\n" {
		t.Fatalf("sidecar referenced by edited directive = %q, %v", got, err)
	}
}

func TestDisablePreservesSidecarAfterWhitespaceDirectiveEdit(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	home := t.TempDir()
	target := templateTargets["foot"]
	directive := target.directives(home)[0]
	sidecar := target.sidecar(home)[0]
	if err := os.MkdirAll(filepath.Dir(directive.file), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(directive.file, []byte("[main]\nfont-size=12\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := EnsureDirective(directive); err != nil {
		t.Fatal(err)
	}
	if err := ApplySidecar(sidecar, "# generated by sysc-shell\n"); err != nil {
		t.Fatal(err)
	}
	config := "[main]\nfont-size=12\ninclude = ~/.config/foot/themes/sysc-shell\n"
	if err := os.WriteFile(directive.file, []byte(config), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := applyTemplateTarget("foot", home, false, "", false, 100); !errors.Is(err, ErrUserModified) {
		t.Fatalf("disable with whitespace-formatted directive = %v, want ErrUserModified", err)
	}
	if got, err := os.ReadFile(sidecar); err != nil || string(got) != "# generated by sysc-shell\n" {
		t.Fatalf("sidecar referenced by whitespace-formatted directive = %q, %v", got, err)
	}
}

// kitty takes the last value of each setting, so the shell's include, written
// last, themes the terminal without displacing the user's own includes. The
// owner chose this on 2026-10-09 over reporting every foreign include, which
// left kitty unthemed beside an ordinary tab-style include (sysc-1077).
func TestApplyEnabledAppendsKittyBesideUserIncludes(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	home := t.TempDir()
	markTemplatesComplete(t, "kitty")
	p := filepath.Join(home, ".config", "kitty", "kitty.conf")
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	user := "font_size 12\ninclude themes/user.conf\n"
	if err := os.WriteFile(p, []byte(user), 0o644); err != nil {
		t.Fatal(err)
	}
	only := func(name string) bool { return name == "kitty" }
	if _, _, err := ApplyEnabled(home, only, theme.Fallback, 100); err != nil {
		t.Fatalf("apply beside a user include = %v", err)
	}
	got, _ := os.ReadFile(p)
	if want := user + "include themes/sysc-shell.conf\n"; string(got) != want {
		t.Fatalf("kitty.conf = %q, want %q", got, want)
	}
}

func TestApplyEnabledForceReplacesDirectiveWithBackup(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	home := t.TempDir()
	markTemplatesComplete(t, "ghostty")
	config := filepath.Join(home, ".config", "ghostty", "config")
	if err := os.MkdirAll(filepath.Dir(config), 0o755); err != nil {
		t.Fatal(err)
	}
	original := "theme = catppuccin\nfont-size = 12\n"
	if err := os.WriteFile(config, []byte(original), 0o600); err != nil {
		t.Fatal(err)
	}
	only := func(name string) bool { return name == "ghostty" }
	outcomes, _, err := ApplyEnabled(home, only, theme.Fallback, 100)
	if err != nil || len(outcomes) != 0 {
		t.Fatalf("forced apply = %v, %v", outcomes, err)
	}
	got, err := os.ReadFile(config)
	if err != nil || !strings.Contains(string(got), "theme = sysc-shell") || !strings.Contains(string(got), "font-size = 12") {
		t.Fatalf("config after force = %q, %v", got, err)
	}
	backup, err := os.ReadFile(config + ".bak")
	if err != nil || string(backup) != original {
		t.Fatalf("config backup = %q, %v", backup, err)
	}
	info, err := os.Stat(config)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o600 {
		t.Fatalf("config mode = %v, want 0600", info.Mode().Perm())
	}
}

func TestKittyPIDsFromProc(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeComm := func(pid, comm string) {
		dir := filepath.Join(root, pid)
		if err := os.Mkdir(dir, 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dir, "comm"), []byte(comm+"\n"), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	writeComm("100", "kitty")
	writeComm("101", "niri")
	writeComm("102", "kitty")
	got := procPIDs(root, "kitty")
	if len(got) != 2 || got[0] != 100 || got[1] != 102 {
		t.Fatalf("kittyPIDs = %v, want [100 102]", got)
	}
}

func TestApplyEnabledSignalsKitty(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	home := t.TempDir()
	markTemplatesComplete(t, "kitty")
	got := make(chan os.Signal, 1)
	signal.Notify(got, syscall.SIGUSR1)
	t.Cleanup(func() { signal.Stop(got) })
	root := t.TempDir()
	dir := filepath.Join(root, strconv.Itoa(os.Getpid()))
	if err := os.Mkdir(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "comm"), []byte("kitty\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	prev := procRoot
	procRoot = root
	t.Cleanup(func() { procRoot = prev })
	only := func(name string) bool { return name == "kitty" }
	if _, _, err := ApplyEnabled(home, only, theme.Fallback, 100); err != nil {
		t.Fatal(err)
	}
	select {
	case <-got:
	case <-time.After(2 * time.Second):
		t.Fatal("kitty process did not receive SIGUSR1")
	}
}

func TestApplyEnabledSingleFlight(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	home := t.TempDir()
	markTemplatesComplete(t, "alacritty")
	only := func(name string) bool { return name == "alacritty" }
	var wg sync.WaitGroup
	wg.Add(2)
	for i := 0; i < 2; i++ {
		go func() {
			defer wg.Done()
			_, _, _ = ApplyEnabled(home, only, theme.Fallback, 100)
		}()
	}
	wg.Wait()
	p := filepath.Join(home, ".config", "alacritty", "alacritty.toml")
	b, err := os.ReadFile(p)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Count(string(b), "import = [") != 1 {
		t.Fatalf("interleaved write: %q", b)
	}
	sidecar, _ := os.ReadFile(filepath.Join(home, ".config", "alacritty", "themes", "sysc-shell.toml"))
	if !strings.Contains(string(sidecar), marker) {
		t.Fatalf("sidecar missing marker: %q", sidecar)
	}
}

func TestApplyEnabledReportsFirstError(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	home := t.TempDir()
	markTemplatesComplete(t, "alacritty")
	p := filepath.Join(home, ".config", "alacritty", "alacritty.toml")
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	// A disabled template still refuses to remove a line naming the shell's
	// theme that it did not write; that refusal is the first error.
	sidecar := filepath.Join(home, ".config", "alacritty", "themes", "sysc-shell.toml")
	if err := os.WriteFile(p, []byte(`import = ["`+sidecar+`"]`+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	none := func(string) bool { return false }
	_, _, err := ApplyEnabled(home, none, theme.Fallback, 100)
	if err == nil {
		t.Fatal("expected skip error")
	}
	if !errors.Is(err, ErrUserModified) {
		t.Fatalf("err = %v", err)
	}
}

func TestApplyEnabledSupersedeUsesLatestHome(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	home1 := t.TempDir()
	markTemplatesComplete(t, "alacritty")
	home2 := t.TempDir()
	started := make(chan struct{})
	block := make(chan struct{})
	first := func(name string) bool {
		if name != "alacritty" {
			return false
		}
		select {
		case <-started:
		default:
			close(started)
		}
		<-block
		return true
	}
	done := make(chan error, 1)
	go func() { _, _, err := ApplyEnabled(home1, first, theme.Fallback, 100); done <- err }()
	select {
	case <-started:
	case <-time.After(2 * time.Second):
		t.Fatal("first apply did not reach alacritty")
	}
	secondDone := make(chan error, 1)
	go func() {
		_, _, err := ApplyEnabled(home2, func(name string) bool { return name == "alacritty" }, theme.Fallback, 100)
		secondDone <- err
	}()
	time.Sleep(20 * time.Millisecond)
	close(block)
	if err := <-done; err != nil {
		t.Fatal(err)
	}
	if err := <-secondDone; err != nil {
		t.Fatal(err)
	}
	p2 := filepath.Join(home2, ".config", "alacritty", "alacritty.toml")
	if _, err := os.Stat(p2); err != nil {
		t.Fatalf("latest home missing alacritty.toml: %v", err)
	}
}

func TestApplyEnabledAndWaitReturnsItsQueuedOutcome(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	home1 := t.TempDir()
	home2 := t.TempDir()
	markTemplatesComplete(t, "alacritty", "foot")
	footSidecar := filepath.Join(home2, ".config", "foot", "themes", "sysc-shell")
	if err := os.MkdirAll(filepath.Dir(footSidecar), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(footSidecar, []byte("user edit\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	started := make(chan struct{})
	block := make(chan struct{})
	defer func() {
		select {
		case <-block:
		default:
			close(block)
		}
	}()
	first := func(name string) bool {
		if name != "alacritty" {
			return false
		}
		select {
		case <-started:
		default:
			close(started)
		}
		<-block
		return true
	}
	firstDone := make(chan struct{})
	go func() {
		_, _, _ = ApplyEnabled(home1, first, theme.Fallback, 100)
		close(firstDone)
	}()
	select {
	case <-started:
	case <-time.After(2 * time.Second):
		t.Fatal("first apply did not reach alacritty")
	}

	type result struct {
		outcomes map[string]error
		adopted  []string
		err      error
	}
	secondDone := make(chan result, 1)
	go func() {
		outcomes, adopted, err := ApplyEnabledAndWait(home2, func(name string) bool { return name == "foot" }, theme.Fallback, 100)
		secondDone <- result{outcomes: outcomes, adopted: adopted, err: err}
	}()
	deadline := time.After(2 * time.Second)
	for {
		applyMu.Lock()
		queued := applyQueued != nil
		applyMu.Unlock()
		if queued {
			break
		}
		select {
		case <-deadline:
			t.Fatal("second apply was not queued")
		case <-time.After(time.Millisecond):
		}
	}

	close(block)
	select {
	case <-firstDone:
	case <-time.After(2 * time.Second):
		t.Fatal("first apply did not finish")
	}
	select {
	case got := <-secondDone:
		// The queued apply returns its own outcome: foot, adopted over the
		// edited sidecar.
		if footErr, attempted := got.outcomes["foot"]; !attempted || footErr != nil || got.err != nil {
			t.Fatalf("second outcomes = %v, err = %v; want foot attempted and applied", got.outcomes, got.err)
		}
		if !slices.Equal(got.adopted, []string{"foot"}) {
			t.Fatalf("second adopted = %v, want foot", got.adopted)
		}
	case <-time.After(2 * time.Second):
		t.Fatal("second apply did not return its outcome")
	}
}

func TestApplyEnabledAndWaitReturnsWhenSuperseded(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	home1 := t.TempDir()
	home2 := t.TempDir()
	home3 := t.TempDir()
	markTemplatesComplete(t, "alacritty", "foot")

	started := make(chan struct{})
	block := make(chan struct{})
	defer func() {
		select {
		case <-block:
		default:
			close(block)
		}
	}()
	first := func(name string) bool {
		if name != "alacritty" {
			return false
		}
		select {
		case <-started:
		default:
			close(started)
		}
		<-block
		return true
	}
	firstDone := make(chan struct{})
	go func() {
		_, _, _ = ApplyEnabled(home1, first, theme.Fallback, 100)
		close(firstDone)
	}()
	select {
	case <-started:
	case <-time.After(2 * time.Second):
		t.Fatal("first apply did not reach alacritty")
	}

	secondDone := make(chan error, 1)
	go func() {
		_, _, err := ApplyEnabledAndWait(home2, func(name string) bool { return name == "foot" }, theme.Fallback, 100)
		secondDone <- err
	}()
	deadline := time.After(2 * time.Second)
	for {
		applyMu.Lock()
		queued := applyQueued != nil && applyQueued.done != nil
		applyMu.Unlock()
		if queued {
			break
		}
		select {
		case <-deadline:
			t.Fatal("second apply was not queued")
		case <-time.After(time.Millisecond):
		}
	}

	if _, _, err := ApplyEnabled(home3, func(name string) bool { return name == "foot" }, theme.Fallback, 100); err != nil {
		t.Fatal(err)
	}
	select {
	case err := <-secondDone:
		if !errors.Is(err, ErrApplySuperseded) {
			t.Fatalf("second error = %v, want superseded", err)
		}
	case <-time.After(2 * time.Second):
		t.Fatal("superseded caller did not return")
	}

	close(block)
	select {
	case <-firstDone:
	case <-time.After(2 * time.Second):
		t.Fatal("first apply did not finish")
	}
	if _, err := os.Stat(filepath.Join(home3, ".config", "foot", "themes", "sysc-shell")); err != nil {
		t.Fatalf("latest queued apply did not run: %v", err)
	}
}

func TestApplyEnabledAndWaitDoesNotWaitForLaterQueuedApply(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	markTemplatesComplete(t, "alacritty")
	home1 := t.TempDir()
	home2 := t.TempDir()
	firstStarted := make(chan struct{})
	firstBlock := make(chan struct{})
	secondStarted := make(chan struct{})
	secondBlock := make(chan struct{})
	var firstStartOnce, firstReleaseOnce, secondStartOnce, secondReleaseOnce sync.Once
	defer func() {
		firstReleaseOnce.Do(func() { close(firstBlock) })
		secondReleaseOnce.Do(func() { close(secondBlock) })
		deadline := time.Now().Add(2 * time.Second)
		for time.Now().Before(deadline) {
			applyMu.Lock()
			busy := applyBusy
			applyMu.Unlock()
			if !busy {
				return
			}
			time.Sleep(time.Millisecond)
		}
		t.Error("apply worker did not become idle")
	}()

	firstDone := make(chan error, 1)
	go func() {
		outcomes, _, err := ApplyEnabledAndWait(home1, func(name string) bool {
			if name == "alacritty" {
				firstStartOnce.Do(func() { close(firstStarted) })
				<-firstBlock
				return true
			}
			return false
		}, theme.Fallback, 100)
		if err == nil {
			var attempted bool
			err, attempted = outcomes["alacritty"]
			if !attempted {
				err = errors.New("first apply returned no alacritty result")
			}
		}
		firstDone <- err
	}()
	select {
	case <-firstStarted:
	case <-time.After(2 * time.Second):
		t.Fatal("first apply did not reach alacritty")
	}

	if _, _, err := ApplyEnabled(home2, func(name string) bool {
		if name == "alacritty" {
			secondStartOnce.Do(func() { close(secondStarted) })
			<-secondBlock
			return true
		}
		return false
	}, theme.Fallback, 100); err != nil {
		t.Fatal(err)
	}
	firstReleaseOnce.Do(func() { close(firstBlock) })
	select {
	case <-secondStarted:
	case <-time.After(2 * time.Second):
		t.Fatal("later queued apply did not start")
	}
	select {
	case err := <-firstDone:
		if err != nil {
			t.Fatalf("first apply = %v", err)
		}
	case <-time.After(2 * time.Second):
		t.Fatal("first waiter blocked behind a later apply")
	}
}

func TestApplyEnabledGatesIncompleteTemplates(t *testing.T) {
	home := t.TempDir()
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	on := func(name string) bool { return true }
	if _, _, err := ApplyEnabled(home, on, theme.Fallback, 100); err != nil {
		t.Fatal(err)
	}
	for _, name := range Catalog().Names() {
		if Complete(name) {
			continue
		}
		targets := []string{writeTarget(home, name)}
		if tgt, ok := templateTargets[name]; ok {
			if tgt.sidecar != nil {
				targets = append(targets, tgt.sidecar(home)...)
			}
			if tgt.block != nil {
				f, _, _ := tgt.block(home)
				targets = append(targets, f)
			}
			for _, dir := range tgt.directives(home) {
				targets = append(targets, dir.file)
			}
		}
		for _, p := range targets {
			if p == "" {
				continue
			}
			if _, err := os.Stat(p); !os.IsNotExist(err) {
				t.Fatalf("incomplete template %s wrote %s (GH #7)", name, p)
			}
		}
	}
}

// The desktop's btop.conf names its own theme. With btop enabled the shell
// themes it anyway and keeps the user's file (sysc-1084).
func TestEnabledBtopIsThemedOverTheUsersTheme(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	home := t.TempDir()
	markTemplatesComplete(t, "btop")
	conf := filepath.Join(home, ".config", "btop", "btop.conf")
	if err := os.MkdirAll(filepath.Dir(conf), 0o755); err != nil {
		t.Fatal(err)
	}
	original := "#? Config file for btop\ncolor_theme = \"noctalia\"\ntheme_background = False\n"
	if err := os.WriteFile(conf, []byte(original), 0o644); err != nil {
		t.Fatal(err)
	}
	only := func(name string) bool { return name == "btop" }
	outcomes, adopted, err := ApplyEnabled(home, only, theme.Fallback, 100)
	if err != nil || len(outcomes) != 0 || !slices.Equal(adopted, []string{"btop"}) {
		t.Fatalf("apply = %v, adopted %v, err %v", outcomes, adopted, err)
	}
	got, _ := os.ReadFile(conf)
	if !strings.Contains(string(got), `color_theme = "sysc-shell"`) || strings.Contains(string(got), "noctalia") ||
		!strings.Contains(string(got), "theme_background = False") {
		t.Fatalf("btop.conf = %q, want the shell's theme and the rest of the user's settings", got)
	}
	if backup, _ := os.ReadFile(conf + ".bak"); string(backup) != original {
		t.Fatalf("btop.conf.bak = %q, want the user's original", backup)
	}
	if got := Backups(home, "btop"); !slices.Equal(got, []string{conf + ".bak"}) {
		t.Fatalf("Backups = %v, want %s", got, conf+".bak")
	}
}

// Adopting replaces the user's theme, never their other settings. Foot keeps
// its other includes; a value spanning several lines (an Alacritty import
// array) is not cut in half, it is reported (sysc-1084).
func TestAdoptionKeepsTheUsersOtherSettings(t *testing.T) {
	t.Run("foot keeps other includes", func(t *testing.T) {
		t.Setenv("XDG_STATE_HOME", t.TempDir())
		home := t.TempDir()
		markTemplatesComplete(t, "foot")
		ini := filepath.Join(home, ".config", "foot", "foot.ini")
		if err := os.MkdirAll(filepath.Dir(ini), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(ini, []byte("[main]\ninclude=~/.config/foot/keys.ini\nfont=Iosevka:size=11\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		if _, _, err := ApplyEnabled(home, func(n string) bool { return n == "foot" }, theme.Fallback, 100); err != nil {
			t.Fatal(err)
		}
		got, _ := os.ReadFile(ini)
		for _, want := range []string{"include=~/.config/foot/keys.ini", "include=~/.config/foot/themes/sysc-shell", "font=Iosevka:size=11"} {
			if !strings.Contains(string(got), want) {
				t.Errorf("foot.ini lost %q:\n%s", want, got)
			}
		}
	})
	t.Run("alacritty multi-line import is reported, not cut", func(t *testing.T) {
		t.Setenv("XDG_STATE_HOME", t.TempDir())
		home := t.TempDir()
		markTemplatesComplete(t, "alacritty")
		toml := filepath.Join(home, ".config", "alacritty", "alacritty.toml")
		if err := os.MkdirAll(filepath.Dir(toml), 0o755); err != nil {
			t.Fatal(err)
		}
		original := "[general]\nimport = [\n  \"~/.config/alacritty/keys.toml\",\n]\n"
		if err := os.WriteFile(toml, []byte(original), 0o644); err != nil {
			t.Fatal(err)
		}
		outcomes, adopted, _ := ApplyEnabled(home, func(n string) bool { return n == "alacritty" }, theme.Fallback, 100)
		if outcomes["alacritty"] == nil || len(adopted) != 0 {
			t.Fatalf("outcomes %v adopted %v, want a reported failure", outcomes, adopted)
		}
		if got, _ := os.ReadFile(toml); string(got) != original {
			t.Fatalf("alacritty.toml rewritten to %q", got)
		}
	})
}
